import type { Language } from './types';

export const translations: Record<Language, any> = {
  en: {
    appName: "AgriMitra",
    activeCrops: "Active Crops",
    waterUsage: "Water Usage",
    estimatedRevenue: "Estimated Revenue",
    yieldForecast: "Yield Forecast",
    farmHealthIndex: "Farm Health Index",
    weatherAdvisory: "Live Weather Advisory",
    temperature: "Temperature",
    humidity: "Humidity",
    rainfall: "Rainfall",
    windSpeed: "Wind Speed",
    condition: "Condition",
    locationDenied: "Location access denied. Showing weather for Delhi.",
    loadingWeather: "Loading weather...",
    pestDiseaseDetection: "Pest & Disease Detection",
    uploadCropImage: "Upload a crop image to detect pests or diseases.",
    upload: "Upload",
    analyzing: "Analyzing...",
    analysisResult: "Analysis Result",
    pestDiseaseName: "Detected Pest/Disease",
    chemicalTreatment: "Chemical Treatment",
    organicTreatment: "Organic Treatment",
    prevention: "Prevention",
    urgencyLevel: "Urgency Level",
    errorPestDetection: "Could not analyze the image. Please try again.",
    noFileSelected: "No file selected",
    govtSchemes: "Government Schemes",
    applyNow: "Apply Now",
    marketPrices: "Market Prices",
    last7Days: "Last 7 Days Trend",
    price: "Price",
    change: "Change",
    apiKeyError: "API Key Error",
    apiKeyMissing: "Weather service is not configured correctly. Please contact an administrator.",
  },
  hi: {
    appName: "एग्रीमित्र",
    activeCrops: "सक्रिय फसलें",
    waterUsage: "पानी का उपयोग",
    estimatedRevenue: "अनुमानित राजस्व",
    yieldForecast: "उपज पूर्वानुमान",
    farmHealthIndex: "खेत स्वास्थ्य सूचकांक",
    weatherAdvisory: "मौसम की ताज़ा जानकारी",
    temperature: "तापमान",
    humidity: "नमी",
    rainfall: "वर्षा",
    windSpeed: "हवा की गति",
    condition: "स्थिति",
    locationDenied: "स्थान की अनुमति नहीं दी गई। दिल्ली का मौसम दिखाया जा रहा है।",
    loadingWeather: "मौसम लोड हो रहा है...",
    pestDiseaseDetection: "कीट और रोग का पता लगाना",
    uploadCropImage: "कीटों या बीमारियों का पता लगाने के लिए फसल की तस्वीर अपलोड करें।",
    upload: "अपलोड करें",
    analyzing: "विश्लेषण हो रहा है...",
    analysisResult: "विश्लेषण परिणाम",
    pestDiseaseName: "पता चला कीट/रोग",
    chemicalTreatment: "रासायनिक उपचार",
    organicTreatment: "जैविक उपचार",
    prevention: "रोकथाम",
    urgencyLevel: "तत्काल स्तर",
    errorPestDetection: "छवि का विश्लेषण नहीं किया जा सका। कृपया पुनः प्रयास करें।",
    noFileSelected: "कोई फ़ाइल नहीं चुनी गई",
    govtSchemes: "सरकारी योजनाएं",
    applyNow: "अभी आवेदन करें",
    marketPrices: "बाजार मूल्य",
    last7Days: "पिछले 7 दिनों का ट्रेंड",
    price: "कीमत",
    change: "बदलाव",
    apiKeyError: "API कुंजी त्रुटि",
    apiKeyMissing: "मौसम सेवा सही ढंग से कॉन्फ़िगर नहीं है। कृपया एक प्रशासक से संपर्क करें।",
  },
  te: {
    appName: "అగ్రిమిత్ర",
    activeCrops: "క్రియాశీల పంటలు",
    waterUsage: "నీటి వినియోగం",
    estimatedRevenue: "అంచనా వేసిన ఆదాయం",
    yieldForecast: "దిగుబడి అంచనా",
    farmHealthIndex: "పొలం ఆరోగ్య సూచిక",
    weatherAdvisory: "ప్రత్యక్ష వాతావరణ సలహా",
    temperature: "ఉష్ణోగ్రత",
    humidity: "తేమ",
    rainfall: "వర్షపాతం",
    windSpeed: "గాలి వేగం",
    condition: "పరిస్థితి",
    locationDenied: "స్థాన ప్రాప్యత నిరాకరించబడింది. ఢిల్లీ వాతావరణం చూపుతోంది.",
    loadingWeather: "వాతావరణం లోడ్ అవుతోంది...",
    pestDiseaseDetection: "పురుగు & వ్యాధి గుర్తింపు",
    uploadCropImage: "పురుగులు లేదా వ్యాధులను గుర్తించడానికి పంట చిత్రాన్ని అప్‌లోడ్ చేయండి.",
    upload: "అప్‌లోడ్ చేయండి",
    analyzing: "విశ్లేషిస్తోంది...",
    analysisResult: "విశ్లేషణ ఫలితం",
    pestDiseaseName: "గుర్తించబడిన పురుగు/వ్యాధి",
    chemicalTreatment: "రసాయన చికిత్స",
    organicTreatment: "సేంద్రీయ చికిత్స",
    prevention: "నివారణ",
    urgencyLevel: "అత్యవసర స్థాయి",
    errorPestDetection: "చిత్రాన్ని విశ్లేషించడం సాధ్యం కాలేదు. దయచేసి మళ్లీ ప్రయత్నించండి.",
    noFileSelected: "ఫైల్ ఎంచుకోలేదు",
    govtSchemes: "ప్రభుత్వ పథకాలు",
    applyNow: "ఇప్పుడే దరఖాస్తు చేసుకోండి",
    marketPrices: "మార్కెట్ ధరలు",
    last7Days: "గత 7 రోజుల ట్రెండ్",
    price: "ధర",
    change: "మార్పు",
    apiKeyError: "API కీ లోపం",
    apiKeyMissing: "వాతావరణ సేవ సరిగ్గా కాన్ఫిగర్ చేయబడలేదు. దయచేసి నిర్వాహకుడిని సంప్రదించండి.",
  },
  ta: {
    appName: "அக்ரிமித்ரா",
    activeCrops: "செயலில் உள்ள பயிர்கள்",
    waterUsage: "நீர் பயன்பாடு",
    estimatedRevenue: "மதிப்பிடப்பட்ட வருவாய்",
    yieldForecast: "விளைச்சல் முன்னறிவிப்பு",
    farmHealthIndex: "பண்ணை சுகாதார குறியீடு",
    weatherAdvisory: "நேரடி வானிலை ஆலோசனை",
    temperature: "வெப்பநிலை",
    humidity: "ஈரப்பதம்",
    rainfall: "மழைப்பொழிவு",
    windSpeed: "காற்றின் வேகம்",
    condition: "நிலைமை",
    locationDenied: "இட அணுகல் மறுக்கப்பட்டது. டெல்லியின் வானிலை காட்டப்படுகிறது.",
    loadingWeather: "வானிலை ஏற்றப்படுகிறது...",
    pestDiseaseDetection: "பூச்சி மற்றும் நோய் கண்டறிதல்",
    uploadCropImage: "பூச்சிகள் அல்லது நோய்களைக் கண்டறிய பயிர் படத்தை பதிவேற்றவும்.",
    upload: "பதிவேற்று",
    analyzing: "பகுப்பாய்வு செய்யப்படுகிறது...",
    analysisResult: "பகுப்பாய்வு முடிவு",
    pestDiseaseName: "கண்டறியப்பட்ட பூச்சி/நோய்",
    chemicalTreatment: "இரசாயன சிகிச்சை",
    organicTreatment: "இயற்கை சிகிச்சை",
    prevention: "தடுப்பு",
    urgencyLevel: "அவசர நிலை",
    errorPestDetection: "படத்தை பகுப்பாய்வு செய்ய முடியவில்லை. மீண்டும் முயற்சிக்கவும்.",
    noFileSelected: "கோப்பு தேர்ந்தெடுக்கப்படவில்லை",
    govtSchemes: "அரசு திட்டங்கள்",
    applyNow: "இப்போது விண்ணப்பிக்கவும்",
    marketPrices: "சந்தை விலைகள்",
    last7Days: "கடைசி 7 நாட்கள் போக்கு",
    price: "விலை",
    change: "மாற்றம்",
    apiKeyError: "API விசை பிழை",
    apiKeyMissing: "வானிலை சேவை சரியாக கட்டமைக்கப்படவில்லை. தயவுசெய்து நிர்வாகியைத் தொடர்பு கொள்ளவும்.",
  },
  mr: {
    appName: "अॅग्रिमित्र",
    activeCrops: "सक्रिय पिके",
    waterUsage: "पाण्याचा वापर",
    estimatedRevenue: "अपेक्षित उत्पन्न",
    yieldForecast: "उत्पादनाचा अंदाज",
    farmHealthIndex: "शेती आरोग्य निर्देशांक",
    weatherAdvisory: "थेट हवामान सल्ला",
    temperature: "तापमान",
    humidity: "आर्द्रता",
    rainfall: "पर्जन्यमान",
    windSpeed: "वाऱ्याचा वेग",
    condition: "स्थिती",
    locationDenied: "स्थान परवानगी नाकारली. दिल्लीचे हवामान दाखवत आहे.",
    loadingWeather: "हवामान लोड होत आहे...",
    pestDiseaseDetection: "कीड आणि रोग ओळख",
    uploadCropImage: "कीड किंवा रोग ओळखण्यासाठी पिकाचे चित्र अपलोड करा.",
    upload: "अपलोड करा",
    analyzing: "विश्लेषण करत आहे...",
    analysisResult: "विश्लेषण परिणाम",
    pestDiseaseName: "ओळखलेली कीड/रोग",
    chemicalTreatment: "रासायनिक उपचार",
    organicTreatment: "सेंद्रिय उपचार",
    prevention: "प्रतिबंध",
    urgencyLevel: "तातडीची पातळी",
    errorPestDetection: "प्रतिमेचे विश्लेषण करू शकलो नाही. कृपया पुन्हा प्रयत्न करा.",
    noFileSelected: "कोणतीही फाईल निवडली नाही",
    govtSchemes: "सरकारी योजना",
    applyNow: "आता अर्ज करा",
    marketPrices: "बाजारभाव",
    last7Days: "मागील ७ दिवसांचा ट्रेंड",
    price: "किंमत",
    change: "बदल",
    apiKeyError: "API की त्रुटी",
    apiKeyMissing: "हवामान सेवा योग्यरित्या कॉन्फिगर केलेली नाही. कृपया प्रशासकाशी संपर्क साधा.",
  },
  bn: {
    appName: "এগ্রিমিত্র",
    activeCrops: "সক্রিয় ফসল",
    waterUsage: "জল ব্যবহার",
    estimatedRevenue: "আনুমানিক রাজস্ব",
    yieldForecast: "ফলন পূর্বাভাস",
    farmHealthIndex: "খামারের স্বাস্থ্য সূচক",
    weatherAdvisory: "লাইভ আবহাওয়ার পরামর্শ",
    temperature: "তাপমাত্রা",
    humidity: "আর্দ্রতা",
    rainfall: "বৃষ্টিপাত",
    windSpeed: "বাতাসের গতি",
    condition: "অবস্থা",
    locationDenied: "অবস্থানের অনুমতি দেওয়া হয়নি। দিল্লির আবহাওয়া দেখানো হচ্ছে।",
    loadingWeather: "আবহাওয়া লোড হচ্ছে...",
    pestDiseaseDetection: "পোকামাকড় ও রোগ সনাক্তকরণ",
    uploadCropImage: "পোকামাকড় বা রোগ সনাক্ত করতে ফসলের একটি ছবি আপলোড করুন।",
    upload: "আপলোড করুন",
    analyzing: "বিশ্লেষণ করা হচ্ছে...",
    analysisResult: "বিশ্লেষণ ফলাফল",
    pestDiseaseName: "শনাক্ত করা পোকামাকড়/রোগ",
    chemicalTreatment: "রাসায়নিক চিকিৎসা",
    organicTreatment: "জৈব চিকিৎসা",
    prevention: "প্রতিরোধ",
    urgencyLevel: "জরুরী স্তর",
    errorPestDetection: "ছবিটি বিশ্লেষণ করা যায়নি। অনুগ্রহ করে আবার চেষ্টা করুন।",
    noFileSelected: "কোনো ফাইল নির্বাচন করা হয়নি",
    govtSchemes: "সরকারি প্রকল্প",
    applyNow: "এখনই আবেদন করুন",
    marketPrices: "বাজারের দাম",
    last7Days: "গত ৭ দিনের ট্রেন্ড",
    price: "দাম",
    change: "পরিবর্তন",
    apiKeyError: "API কী ত্রুটি",
    apiKeyMissing: "আবহাওয়া পরিষেবা সঠিকভাবে কনফিগার করা হয়নি। অনুগ্রহ করে একজন প্রশাসকের সাথে যোগাযোগ করুন।",
  },
  pa: {
    appName: "ਐਗਰੀਮਿੱਤਰ",
    activeCrops: "ਸਰਗਰਮ ਫਸਲਾਂ",
    waterUsage: "ਪਾਣੀ ਦੀ ਵਰਤੋਂ",
    estimatedRevenue: "ਅਨੁਮਾਨਿਤ ਆਮਦਨ",
    yieldForecast: "ਝਾੜ ਦੀ ਭਵਿੱਖਬਾਣੀ",
    farmHealthIndex: "ਖੇਤ ਸਿਹਤ ਸੂਚਕਾਂਕ",
    weatherAdvisory: "ਲਾਈਵ ਮੌਸਮ ਸਲਾਹ",
    temperature: "ਤਾਪਮਾਨ",
    humidity: "ਨਮੀ",
    rainfall: "ਬਾਰਸ਼",
    windSpeed: "ਹਵਾ ਦੀ ਗਤੀ",
    condition: "ਸਥਿਤੀ",
    locationDenied: "ਸਥਾਨ ਦੀ ਇਜਾਜ਼ਤ ਨਹੀਂ ਦਿੱਤੀ ਗਈ। ਦਿੱਲੀ ਦਾ ਮੌਸਮ ਦਿਖਾਇਆ ਜਾ ਰਿਹਾ ਹੈ।",
    loadingWeather: "ਮੌਸਮ ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...",
    pestDiseaseDetection: "ਕੀੜੇ ਅਤੇ ਬਿਮਾਰੀ ਦੀ ਪਛਾਣ",
    uploadCropImage: "ਕੀੜਿਆਂ ਜਾਂ ਬਿਮਾਰੀਆਂ ਦਾ ਪਤਾ ਲਗਾਉਣ ਲਈ ਫਸਲ ਦੀ ਤਸਵੀਰ ਅੱਪਲੋਡ ਕਰੋ।",
    upload: "ਅੱਪਲੋਡ ਕਰੋ",
    analyzing: "ਵਿਸ਼ਲੇਸ਼ਣ ਕੀਤਾ ਜਾ ਰਿਹਾ ਹੈ...",
    analysisResult: "ਵਿਸ਼ਲੇਸ਼ਣ ਨਤੀਜਾ",
    pestDiseaseName: "ਪਛਾਣਿਆ ਗਿਆ ਕੀਟ/ਬਿਮਾਰੀ",
    chemicalTreatment: "ਰਸਾਇਣਕ ਇਲਾਜ",
    organicTreatment: "ਜੈਵਿਕ ਇਲਾਜ",
    prevention: "ਰੋਕਥਾਮ",
    urgencyLevel: "ਤੁਰੰਤ ਪੱਧਰ",
    errorPestDetection: "ਚਿੱਤਰ ਦਾ ਵਿਸ਼ਲੇਸ਼ਣ ਨਹੀਂ ਕੀਤਾ ਜਾ ਸਕਿਆ। ਕਿਰਪਾ ਕਰਕੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।",
    noFileSelected: "ਕੋਈ ਫਾਈਲ ਨਹੀਂ ਚੁਣੀ ਗਈ",
    govtSchemes: "ਸਰਕਾਰੀ ਯੋਜਨਾਵਾਂ",
    applyNow: "ਹੁਣੇ ਅਰਜ਼ੀ ਦਿਓ",
    marketPrices: "ਬਾਜ਼ਾਰ ਦੀਆਂ ਕੀਮਤਾਂ",
    last7Days: "ਪਿਛਲੇ 7 ਦਿਨਾਂ ਦਾ ਰੁਝਾਨ",
    price: "ਕੀਮਤ",
    change: "ਬਦਲਾਅ",
    apiKeyError: "API ਕੁੰਜੀ ਗਲਤੀ",
    apiKeyMissing: "ਮੌਸਮ ਸੇਵਾ ਸਹੀ ਢੰਗ ਨਾਲ ਕੌਂਫਿਗਰ ਨਹੀਂ ਕੀਤੀ ਗਈ ਹੈ। ਕਿਰਪਾ ਕਰਕੇ ਕਿਸੇ ਪ੍ਰਸ਼ਾਸਕ ਨਾਲ ਸੰਪਰਕ ਕਰੋ।",
  },
  gu: {
    appName: "એગ્રીમિત્ર",
    activeCrops: "સક્રિય પાક",
    waterUsage: "પાણીનો વપરાશ",
    estimatedRevenue: "અંદાજિત આવક",
    yieldForecast: "ઉપજની આગાહી",
    farmHealthIndex: "ખેતર આરોગ્ય સૂચકાંક",
    weatherAdvisory: "જીવંત હવામાન સલાહ",
    temperature: "તાપમાન",
    humidity: "ભેજ",
    rainfall: "વરસાદ",
    windSpeed: "પવનની ગતિ",
    condition: "સ્થિતિ",
    locationDenied: "સ્થાનની ઍક્સેસ નકારી. દિલ્હી માટે હવામાન બતાવી રહ્યું છે.",
    loadingWeather: "હવામાન લોડ કરી રહ્યું છે...",
    pestDiseaseDetection: "જીવાત અને રોગની શોધ",
    uploadCropImage: "જીવાતો અથવા રોગોને શોધવા માટે પાકનો ફોટો અપલોડ કરો.",
    upload: "અપલોડ કરો",
    analyzing: "વિશ્લેષણ કરી રહ્યું છે...",
    analysisResult: "વિશ્લેષણ પરિણામ",
    pestDiseaseName: "શોધાયેલ જીવાત/રોગ",
    chemicalTreatment: "રાસાયણિક સારવાર",
    organicTreatment: "ઓર્ગેનિક સારવાર",
    prevention: "નિવારણ",
    urgencyLevel: "તાકીદનું સ્તર",
    errorPestDetection: "છબીનું વિશ્લેષણ કરી શકાયું નથી. કૃપા કરીને ફરી પ્રયાસ કરો.",
    noFileSelected: "કોઈ ફાઇલ પસંદ નથી",
    govtSchemes: "સરકારી યોજનાઓ",
    applyNow: "હવે અરજી કરો",
    marketPrices: "બજાર ભાવ",
    last7Days: "છેલ્લા 7 દિવસનો ટ્રેન્ડ",
    price: "કિંમત",
    change: "ફેરફાર",
    apiKeyError: "API કી ભૂલ",
    apiKeyMissing: "હવામાન સેવા યોગ્ય રીતે ગોઠવેલ નથી. કૃપા કરીને વ્યવસ્થાપકનો સંપર્ક કરો.",
  },
  kn: {
    appName: "ಅಗ್ರಿಮಿತ್ರ",
    activeCrops: "ಸಕ್ರಿಯ ಬೆಳೆಗಳು",
    waterUsage: "ನೀರಿನ ಬಳಕೆ",
    estimatedRevenue: "ಅಂದಾಜು ಆದಾಯ",
    yieldForecast: "ಇಳುವರಿ ಮುನ್ಸೂಚನೆ",
    farmHealthIndex: "ಕೃಷಿ ಆರೋಗ್ಯ ಸೂಚ್ಯಂಕ",
    weatherAdvisory: "ನೇರ ಹವಾಮಾನ ಸಲಹೆ",
    temperature: "ತಾಪಮಾನ",
    humidity: "ತೇವಾಂಶ",
    rainfall: "ಮಳೆ",
    windSpeed: "ಗಾಳಿಯ ವೇಗ",
    condition: "ಸ್ಥಿತಿ",
    locationDenied: "ಸ್ಥಳ ಪ್ರವೇಶವನ್ನು ನಿರಾಕರಿಸಲಾಗಿದೆ. ದೆಹಲಿಯ ಹವಾಮಾನವನ್ನು ತೋರಿಸಲಾಗುತ್ತಿದೆ.",
    loadingWeather: "ಹವಾಮಾನ ಲೋಡ್ ಆಗುತ್ತಿದೆ...",
    pestDiseaseDetection: "ಕೀਟ ಮತ್ತು ರೋಗ ಪತ್ತೆ",
    uploadCropImage: "ಕೀಟಗಳು ಅಥವಾ ರೋಗಗಳನ್ನು ಪತ್ತೆಹಚ್ಚಲು ಬೆಳೆಯ ಚಿತ್ರವನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ.",
    upload: "ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
    analyzing: "ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತಿದೆ...",
    analysisResult: "ವಿಶ್ಲೇಷಣೆ ಫಲಿತಾಂಶ",
    pestDiseaseName: "ಪತ್ತೆಯಾದ ಕೀಟ/ರೋಗ",
    chemicalTreatment: "ರಾಸಾಯನಿಕ ಚಿಕಿತ್ಸೆ",
    organicTreatment: "ಸಾವಯವ ಚಿಕಿತ್ಸೆ",
    prevention: "ತಡೆಗಟ್ಟುವಿಕೆ",
    urgencyLevel: "ತುರ್ತು ಮಟ್ಟ",
    errorPestDetection: "ಚಿತ್ರವನ್ನು ವಿಶ್ಲೇಷಿಸಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
    noFileSelected: "ಯಾವುದೇ ಫೈಲ್ ಆಯ್ಕೆ ಮಾಡಲಾಗಿಲ್ಲ",
    govtSchemes: "ಸರ್ಕಾರಿ ಯೋಜನೆಗಳು",
    applyNow: "ಈಗ ಅನ್ವಯಿಸಿ",
    marketPrices: "ಮಾರುಕಟ್ಟೆ ಬೆಲೆಗಳು",
    last7Days: "ಕಳೆದ 7 ದಿನಗಳ ಪ್ರವೃತ್ತಿ",
    price: "ಬೆಲೆ",
    change: "ಬದಲಾವಣೆ",
    apiKeyError: "API ಕೀ ದೋಷ",
    apiKeyMissing: "ಹವಾಮಾನ ಸೇವೆಯನ್ನು ಸರಿಯಾಗಿ ಕಾನ್ಫಿಗರ್ ಮಾಡಲಾಗಿಲ್ಲ. ದಯವಿಟ್ಟು ನಿರ್ವಾಹಕರನ್ನು ಸಂಪರ್ಕಿಸಿ.",
  },
  ml: {
    appName: "അഗ്രിമിത്ര",
    activeCrops: "സജീവ വിളകൾ",
    waterUsage: "ജല ഉപയോഗം",
    estimatedRevenue: "കണക്കാക്കിയ വരുമാനം",
    yieldForecast: "വിളവ് പ്രവചനം",
    farmHealthIndex: "ഫാം ആരോഗ്യ സൂചിക",
    weatherAdvisory: "തത്സമയ കാലാവസ്ഥാ ഉപദേശം",
    temperature: "താപനില",
    humidity: "ഈർപ്പം",
    rainfall: "മഴ",
    windSpeed: "കാറ്റിന്റെ വേഗത",
    condition: "അവസ്ഥ",
    locationDenied: "ലൊക്കേഷൻ ആക്സസ് നിഷേധിച്ചു. ഡൽഹിയിലെ കാലാവസ്ഥ കാണിക്കുന്നു.",
    loadingWeather: "കാലാവസ്ഥ ലോഡുചെയ്യുന്നു...",
    pestDiseaseDetection: "കീട രോഗ നിർണ്ണയം",
    uploadCropImage: "കീടങ്ങളെയോ രോഗങ്ങളെയോ കണ്ടെത്താൻ വിളയുടെ ചിത്രം അപ്‌ലോഡ് ചെയ്യുക.",
    upload: "അപ്‌ലോഡ് ചെയ്യുക",
    analyzing: "വിശകലനം ചെയ്യുന്നു...",
    analysisResult: "വിശകലന ഫലം",
    pestDiseaseName: "കണ്ടെത്തിയ കീടം/രോഗം",
    chemicalTreatment: "രാസ ചികിത്സ",
    organicTreatment: "ജൈവ ചികിത്സ",
    prevention: "പ്രതിരോധം",
    urgencyLevel: "അടിയന്തര നില",
    errorPestDetection: "ചിത്രം വിശകലനം ചെയ്യാൻ കഴിഞ്ഞില്ല. ദയവായി വീണ്ടും ശ്രമിക്കുക.",
    noFileSelected: "ഫയൽ തിരഞ്ഞെടുത്തിട്ടില്ല",
    govtSchemes: "സർക്കാർ പദ്ധതികൾ",
    applyNow: "ഇപ്പോൾ അപേക്ഷിക്കുക",
    marketPrices: "വിപണി വിലകൾ",
    last7Days: "കഴിഞ്ഞ 7 ദിവസത്തെ പ്രവണത",
    price: "വില",
    change: "മാറ്റം",
    apiKeyError: "API കീ പിശക്",
    apiKeyMissing: "കാലാവസ്ഥാ സേവനം ശരിയായി കോൺഫിഗർ ചെയ്തിട്ടില്ല. ഒരു അഡ്മിനിസ്ട്രേറ്ററുമായി ബന്ധപ്പെടുക.",
  },
  or: {
    appName: "ଏଗ୍ରିମିତ୍ର",
    activeCrops: "ସକ୍ରିୟ ଫସଲ",
    waterUsage: "ଜଳ ବ୍ୟବହାର",
    estimatedRevenue: "ଆନୁମାନିକ ରାଜସ୍ୱ",
    yieldForecast: "ଅମଳ ପୂର୍ବାନୁମାନ",
    farmHealthIndex: "ଫାର୍ମ ସ୍ୱାସ୍ଥ୍ୟ ସୂଚକାଙ୍କ",
    weatherAdvisory: "ଲାଇଭ୍ ପାଣିପାଗ ପରାମର୍ଶ",
    temperature: "ତାପମାତ୍ରା",
    humidity: "ଆର୍ଦ୍ରତା",
    rainfall: "ବର୍ଷା",
    windSpeed: "ପବନର ଗତି",
    condition: "ଅବସ୍ଥା",
    locationDenied: "ସ୍ଥାନ ଅନୁମତି ଅଗ୍ରାହ୍ୟ କରାଯାଇଛି। ଦିଲ୍ଲୀ ପାଇଁ ପାଣିପାଗ ଦେଖାଉଛି।",
    loadingWeather: "ପାଣିପାଗ ଲୋଡ୍ ହେଉଛି...",
    pestDiseaseDetection: "କୀଟ ଏବଂ ରୋଗ ଚିହ୍ନଟ",
    uploadCropImage: "କୀଟ କିମ୍ବା ରୋଗ ଚିହ୍ନଟ କରିବାକୁ ଫସଲର ଏକ ଚିତ୍ର ଅପଲୋଡ୍ କରନ୍ତୁ।",
    upload: "ଅପଲୋଡ୍ କରନ୍ତୁ",
    analyzing: "ବିଶ୍ଳେଷଣ କରୁଛି...",
    analysisResult: "ବିଶ୍ଳେଷଣ ଫଳାଫଳ",
    pestDiseaseName: "ଚିହ୍ନଟ ହୋଇଥିବା କୀଟ/ରୋଗ",
    chemicalTreatment: "ରାସାୟନିକ ଚିକିତ୍ସା",
    organicTreatment: "ଜୈବିକ ଚିକିତ୍ସା",
    prevention: "ପ୍ରତିରୋଧ",
    urgencyLevel: "ଜରୁରୀ ସ୍ତର",
    errorPestDetection: "ଚିତ୍ରକୁ ବିଶ୍ଳେଷଣ କରାଯାଇପାରିଲା ନାହିଁ। ଦୟାକରି ପୁଣି ଚେଷ୍ଟା କରନ୍ତୁ।",
    noFileSelected: "କୌଣସି ଫାଇଲ୍ ଚୟନ କରାଯାଇ ନାହିଁ",
    govtSchemes: "ସରକାରୀ ଯୋଜନା",
    applyNow: "ବର୍ତ୍ତମାନ ଆବେଦନ କରନ୍ତୁ",
    marketPrices: "ବଜାର ମୂଲ୍ୟ",
    last7Days: "ଗତ ୭ ଦିନର ଟ୍ରେଣ୍ଡ",
    price: "ମୂଲ୍ୟ",
    change: "ପରିବର୍ତ୍ତନ",
    apiKeyError: "API କୀ ତ୍ରୁଟି",
    apiKeyMissing: "ପାଣିପାଗ ସେବା ସଠିକ୍ ଭାବରେ ସଂରଚିତ ହୋଇନାହିଁ। ଦୟାକରି ଜଣେ ପ୍ରଶାସକଙ୍କ ସହିତ ଯୋଗାଯୋଗ କରନ୍ତୁ।",
  },
};

export const getTranslation = (lang: Language, key: string): string => {
  return translations[lang]?.[key] || translations['en'][key];
};